name: Another workflow

on:
  pull_request:

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
      - 
        name: install dependencies
        shell: bash
        run: |
          lsls
          
      - 
        name: install dependencies
        shell: bash
        run: |
          ls
          lssss
          
      
