name: Another workflow

on:
  pull_request:
  push:

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
      - 
        name: install dependencies
        shell: bash
        run: |
          time docker pull ghcr.io/armmbed/mbed-os-env:master-latest
          ls
          
      - 
        name: install dependencies
        shell: bash
        run: |
          ls
          lsls
          ls
          
      
