name: Another workflow

on:
  pull_request:
  push:

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
      - 
        name: install dependencies
        shell: bash
        run: |
          ls
          
      - 
        name: install dependencies
        shell: bash
        run: |
          ls
          ls
          
      
