name: PR Basic Checks

on:
  pull_request:

jobs:
  pr-head:
    runs-on: ubuntu-latest

    steps:
      - 
        name: install dependencies
        shell: bash
        run: |
          ls
          sleep 120
      - 
        name: install dependencies
        shell: bash
        run: |
          ls

  jenkins-ci_test:
    runs-on: ubuntu-latest

    steps:
      - 
        name: install dependencies
        shell: bash
        run: |
          ls
          
      - 
        name: install dependencies
        shell: bash
        run: |
          ls



          