name: a workflow existing in base repo

on:
  pull_request: 

jobs: 
  test-job:

    runs-on: ubuntu-latest

    steps:
      -
        name: test-step
        run: |
          set -e
          echo "test"
